# Generated by Django 4.1.7 on 2023-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecommercehub',
            options={'verbose_name': 'Hub', 'verbose_name_plural': 'Hubs'},
        ),
        migrations.RemoveField(
            model_name='ecommercehub',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ecommercehub',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ecommercehub',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ecommercehub',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ecommercehub',
            name='vtex_id',
        ),
        migrations.AddField(
            model_name='ecommercehub',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Api Key'),
        ),
        migrations.AddField(
            model_name='ecommercehub',
            name='api_token',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Api token'),
        ),
        migrations.AddField(
            model_name='ecommercehub',
            name='platfrom',
            field=models.CharField(choices=[('vtex', 'VTEX')], default='vtex', max_length=50, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='ecommercehub',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
