# Generated by Django 4.1.7 on 2023-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ecommercehub_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercebrand',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish')], default='pending', max_length=10, verbose_name='State'),
        ),
    ]
