# Generated by Django 4.1.7 on 2023-03-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ecommercebrand_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommercebrand',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ecommercebrand',
            name='symbol',
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='active',
            field=models.BooleanField(default=True, max_length=3, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='description',
            field=models.TextField(blank=True, max_length=3, null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='link',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Link ID'),
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ecommercehub', verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='title',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ecommercebrand',
            name='vtex_id',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Vtex ID'),
        ),
        migrations.AlterField(
            model_name='ecommercebrand',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
