# Generated by Django 4.1.7 on 2023-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_ecommercebrand_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercebrand',
            name='active',
            field=models.BooleanField(default=True, max_length=250, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ecommercebrand',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ecommercebrand',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link ID'),
        ),
        migrations.AlterField(
            model_name='ecommercebrand',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ecommercebrand',
            name='vtex_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Vtex ID'),
        ),
    ]
