# Generated by Django 4.1.7 on 2023-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ecommercebrand_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='vtex_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vtes ID'),
        ),
    ]
