# Generated by Django 4.1.7 on 2023-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_ecommercecategory_vtex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='mtto',
            field=models.CharField(choices=[('LIST', 'List of SKUs'), ('COMBO', 'Combo Boxes'), ('RADIO', 'Icons with radio selection (radio box)'), ('SPECIFICATION', 'Following definition of SKU specification')], max_length=20, verbose_name='Mtto'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish')], default='pending', max_length=10, verbose_name='State'),
        ),
    ]
