# Generated by Django 4.1.7 on 2023-04-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_ecommercecategory_mtto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='global_category',
            field=models.IntegerField(max_length=200, verbose_name='ID Categoría global'),
        ),
    ]
