# Generated by Django 4.1.7 on 2023-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_ecommercecategory_global_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercecategory',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Has Children'),
        ),
        migrations.AddField(
            model_name='ecommercecategory',
            name='is_deparment',
            field=models.BooleanField(default=False, verbose_name='Has Children'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='global_category',
            field=models.IntegerField(verbose_name='ID Categoría global'),
        ),
    ]
