# Generated by Django 4.1.7 on 2023-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ecommercecategory_has_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommercecategory',
            name='is_deparment',
        ),
        migrations.AddField(
            model_name='ecommercecategory',
            name='is_department',
            field=models.BooleanField(default=False, verbose_name='Is department'),
        ),
    ]
