# Generated by Django 4.1.7 on 2023-04-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_ecommercecategory_is_deparment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='global_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Categoría global'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='mtto',
            field=models.CharField(blank=True, choices=[('LIST', 'List of SKUs'), ('COMBO', 'Combo Boxes'), ('RADIO', 'Icons with radio selection (radio box)'), ('SPECIFICATION', 'Following definition of SKU specification')], max_length=20, null=True, verbose_name='Mtto'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='remarketing_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarketing Code'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='show_brand_filter',
            field=models.BooleanField(blank=True, null=True, verbose_name='Show brand filter'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='showing_storefront',
            field=models.BooleanField(blank=True, null=True, verbose_name='Showing Storefront'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='store_front_link',
            field=models.BooleanField(blank=True, null=True, verbose_name='Store Front Link'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
