# Generated by Django 4.1.7 on 2023-04-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_ecommercecategory_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='show_brand_filter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Show brand filter'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='showing_storefront',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Showing Storefront'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='store_front_link',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Store Front Link'),
        ),
    ]
