# Generated by Django 4.1.7 on 2023-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_ecommercecategory_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='show_brand_filter',
            field=models.BooleanField(default=False, verbose_name='Show brand filter'),
        ),
        migrations.AlterField(
            model_name='ecommercecategory',
            name='store_front_link',
            field=models.BooleanField(default=False, verbose_name='Store Front Link'),
        ),
    ]
