# Generated by Django 4.1.7 on 2023-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_ecommercecategory_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecategory',
            name='showing_storefront',
            field=models.BooleanField(default=False, verbose_name='Showing Storefront'),
        ),
    ]
