# Generated by Django 4.1.7 on 2023-04-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_ecommercecategory_showing_storefront'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
