# Generated by Django 4.1.7 on 2023-04-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ecommercecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercewarehouse',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish')], default='pending', max_length=10, verbose_name='State'),
        ),
    ]
