# Generated by Django 4.1.7 on 2023-04-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_ecommercewarehouse_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercewarehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ecommercewarehouse',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ecommercewarehouse',
            name='vtex_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vtes ID'),
        ),
    ]
